Feat/create avatar component
zenorocha/react-email pull request #139
Opened 2022-10-03 17:22 UTC by petersonmedina

2022-10-03 17:37 UTC, luanmuniz commented on packages/avatar/src/avatar.tsx
> +  width: '60px',
I think size is a pretty important configuration parameter. This would be great as an additional prop!

2022-10-03 17:37 UTC, luanmuniz commented on packages/avatar/src/avatar.tsx
> +  display: 'grid',
According to this, grid is not a very well supported thing in emails: 
https://designmodo.com/html-css-emails/#flexbox-or-grid-layout

2022-10-03 17:37 UTC, luanmuniz commented on packages/avatar/src/avatar.tsx
> +  backgroundImage: '',
Does an empty variable serves a specific function here or should we clean it?

2022-10-03 17:37 UTC, luanmuniz commented on packages/avatar/src/avatar.tsx
> +  borderRadius: '100%',
Maybe border-radius can be a prop too. I think we should make these components as flexible as we can, we never know how the next user will use them.

2022-10-03 22:20 UTC, bukinoshita commented on packages/avatar/readme.md
> +![React Email img cover](https://react-email-assets.vercel.app/img.png)
```suggestion
![React Email avatar cover](https://react-email-assets.vercel.app/avatar.png)
```

2022-10-03 22:21 UTC, bukinoshita commented on packages/avatar/src/avatar.spec.tsx
> +    const actualOutput = render(<Avatar src="cat.jpg" name=" My Cat" />);
Can we also use a real source? Maybe from https://plaiceholder.co/
```suggestion
    const actualOutput = render(<Avatar src="cat.jpg" name="My Cat" />);
```

2022-10-03 22:22 UTC, bukinoshita commented on packages/avatar/src/avatar.tsx
> +      </>
We can remove the fragment here.
```suggestion
        <span
          style={avatarContainer}
          ref={forwardedRef}
          {...props}
        >
          <label style={avatarLabel}>{abbreviete(name)}</label>
          <span style={avatarImg}></span>
        </span>
```

2022-10-03 22:29 UTC, bukinoshita requested changes
Thanks for opening the Avatar component PR, this will be a great component.

A few nits:

1. We can remove most of the styling since this looks pretty opinionated. It would be better to let the user use the styling they need/want instead.

2. I think for the Avatar API we should separate it into the `AvatarRoot`, `AvatarImage` and `AvatarFallback`.

Eg:

```tsx
<Avatar>
  <Avatar.Image src="https://images.unsplash.com/photo-1664710696502-69589bfc2ef6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzM3x8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60" alt="Image" />
  <Avatar.Fallback>Image</Avatar.Fallback>
</Avatar>
```

3. Can you rename the PR title?
```diff
- Feat/create avatar component
+ feat(avatar): Create Avatar component
```

2022-10-04 13:22 UTC, petersonmedina commented
> 
I don't know how to use img tag without having to use async because of rendering, do you have any ideas?

2022-10-04 14:56 UTC, bukinoshita commented
> > 
> 
> I don't know how to use img tag without having to use async because of rendering, do you have any ideas @bukinoshita ?

What do you mean by having it async?

2022-10-04 15:25 UTC, petersonmedina commented
> 

for me to use the lib https://plaiceholder.co/ or create some function that checks if the src is valid I thought of doing it using async/await but the render generates the code before finishing

2022-10-13 03:28 UTC, merged

2022-10-13 04:43 UTC, zenorocha commented
Awesome stuff @petersonmedina!

* Added the <Avatar /> component to the preview template:https://github.com/zenorocha/react-email/commit/14026e8a7c9ebbc105444d28f22c352eb1f2b007
* Published to npm: https://www.npmjs.com/package/@react-email/avatar
* Suggested an interface change: https://github.com/zenorocha/react-email/issues/140