Add Change URL when moving from Desktop/Source
zenorocha/react-email pull request #245
Opened 2022-12-18 00:39 UTC by EmersonGarrido

To facilitate sharing, I added via url the parameter view with desktop mode and source @zenorocha 
https://github.com/zenorocha/react-email/issues/244

Thanks

2022-12-18 00:46 UTC, bukinoshita requested changes
Hey @EmersonGarrido , thanks for opening the PR.

I think it would be better to have the change [here](https://github.com/zenorocha/react-email/blob/main/packages/react-email/preview/src/pages/preview/%5Bslug%5D.tsx#L59) instead of a `useEffect`.

Whenever a user changes the `viewMode` it should we `router.push` to that route with a query of that mode.

2022-12-18 01:27 UTC, EmersonGarrido commented
I removed one of the useEffect but there is still a need for one of them to get the share url every time the user comes through it.

give a feel how it turned out.

2022-12-18 13:43 UTC, bukinoshita commented on packages/react-email/preview/src/pages/preview/[slug].tsx
> +  useEffect(() => {
We should have the `React` prefix here to follow the pattern.

```suggestion
  React.useEffect(() => {
```

2022-12-18 13:43 UTC, bukinoshita commented on packages/react-email/preview/src/pages/preview/[slug].tsx
> +import { useEffect } from 'react';
We're already importing `React` above.
```suggestion
```

2022-12-18 13:45 UTC, bukinoshita commented on packages/react-email/preview/src/pages/preview/[slug].tsx
> +        view: `${mode}`,
We can use only the variable here.
```suggestion
        view: mode,
```

2022-12-19 11:54 UTC, EmersonGarrido reviewed
I made the necessary changes to the code.

2022-12-21 11:05 UTC, merged